from .get_all_debates import get_all_debates
from .insert_debate import insert_debate
from .get_tournaments import get_tournaments
from .get_speaker import get_speaker
from .import_records import import_records
from .delete_record import delete_record
from .get_user_tournaments import get_user_tournaments
from .create_user_tournament import create_user_tournament
from .get_start_date import get_start_date
from .delete_tournament import delete_tournament
from .import_wsdc_records import import_wsdc_records
from .import_australs_records import import_australs_records
from .refresh_tournament import refresh_tournament
from .get_cats_for_debate import get_cats_for_debate
from .set_cats_for_debate import set_cats_for_debate