# 1. Use a small sentence transformer
import argparse
from pathlib import Path
import os
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
import joblib
import json
from tqdm import tqdm

### THIS CODE IS NOT RUN ###

### This is the code I used to train my model. It has at least partially been generated by AI.


def parse_args():
    parser = argparse.ArgumentParser(description="Train the debate motion classifier")
    parser.add_argument(
        "--motions-json",
        dest="motions_json",
        default=os.getenv("MOTION_DATA_PATH"),
        help="Path to the training JSON file containing motions and labels.",
    )
    parser.add_argument(
        "--artifacts-dir",
        dest="artifacts_dir",
        default=os.getenv("MODEL_ARTIFACT_DIR", "."),
        help="Directory where the trained pickle files will be written.",
    )
    args = parser.parse_args()
    if not args.motions_json:
        parser.error("--motions-json or MOTION_DATA_PATH is required")
    return args


def main():
    args = parse_args()
    motion_data_path = Path(args.motions_json).expanduser().resolve()
    artifact_dir = Path(args.artifacts_dir).expanduser().resolve()
    artifact_dir.mkdir(parents=True, exist_ok=True)

    model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")  # ~80 MB

    with motion_data_path.open("r") as f:
        big_json = json.load(f)

    train_texts = []
    train_labels = []

    print("creating lists")
    for motion in tqdm(big_json):
        train_texts.append(motion["Infoslide"] + motion["Motion"])
        train_labels.append(motion["Types"])

    # 2. Encode text
    print("encoding")
    X_train = model.encode(train_texts)

    # 3. Encode labels
    mlb = MultiLabelBinarizer()
    y_train = mlb.fit_transform(train_labels)

    # 4. Train multi‑label classifier
    print("training")
    clf = OneVsRestClassifier(LogisticRegression(class_weight=None, max_iter=1000))
    tqdm(clf.fit(X_train, y_train))

    # 5. Predict
    def classify(text):
        X = model.encode([text])
        pred = clf.predict_proba(X)[0]
        categories = mlb.classes_[pred >= 0.99].tolist()
        return categories

    joblib.dump(model, artifact_dir / "sentence_transformer.pkl")
    joblib.dump(mlb, artifact_dir / "multilabel_binarizer.pkl")
    joblib.dump(clf, artifact_dir / "classifier.pkl")

    # Test
    print(classify("The government should raise interest rates and protect free speech."))


if __name__ == "__main__":
    main()