import joblib
from fastapi import Request

# This code was at least partly generated by AI. 

def classify(info_slide: str, motion: str, request: Request):
    """
    Classify motion, returning the classified data
    
    :param info_slide: Motion infoslides
    :type info_slide: str
    :param motion: Motion
    :type motion: str
    :param request: request
    :type request: Request
    """
    model = request.app.state.model
    mlb = request.app.state.mlb
    clf = request.app.state.clf
    # Encode text
    # This is the way I trained my model, but alter accordingly
    text = info_slide + motion
    X = model.encode([text])
    
    # Predict binary labels
    pred = clf.predict_proba(X)[0]
    
    # Convert back to category names
    categories = mlb.classes_[pred >= 0.3].tolist()
    
    return categories